DROP TABLE if exists AKTIVEORDRER;
DROP TABLE if exists ORDREHISTORIK;
DROP TABLE if exists PIZZAER;
DROP TABLE if exists ORDRER;


CREATE TABLE PIZZAER (  
    PIZZANUMMER INTEGER not null, 
    PIZZANAVN VARCHAR(30), 
    PIZZAPRIS double not null, 
    PRIMARY KEY (PIZZANUMMER)
);

insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (1, "Vesuvio", 57.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (2, "Amerikaner", 53.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (3, "Cacciatore", 57.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (4, "Carbona", 63.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (5, "Dennis", 65.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (6, "Bertil", 57.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (7, "Silvia", 61.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (8, "Victoria", 61.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (9, "Toronfo", 61.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (10, "Capricciosa", 61.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (11, "Hawai", 61.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (12, "Le Blissola", 61.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (13, "Venezia", 61.0);
insert into PIZZAER (PIZZANUMMER,PIZZANAVN,PIZZAPRIS) values (14, "Mafia", 61.0);


CREATE TABLE AKTIVEORDRER (
    ORDRENUMMER INT NOT NULl AUTO_INCREMENT,
    FÆRDIG TINYINT,
    DATOOPRETTET TIMESTAMP,
    DATOFÆRDIG DATETIME,
    PIZZANUMMER INTEGER not null,
    PRIMARY KEY (ORDRENUMMER),
    FOREIGN KEY (PIZZANUMMER) REFERENCES PIZZAER(PIZZANUMMER)
);

insert into AKTIVEORDRER (ORDRENUMMER, FÆRDIG, DATOOPRETTET, DATOFÆRDIG, PIZZANUMMER) values (ORDRENUMMER, 0, now(), now()+10, 1);

CREATE TABLE ORDREHISTORIK (
    ORDRENUMMER INT NOT NULl AUTO_INCREMENT,
    FÆRDIG TINYINT,
    DATO TIMESTAMP,
    PRIMARY KEY (ORDRENUMMER)
);

insert into ORDREHISTORIK(ORDRENUMMER, FÆRDIG, DATO) values (1, 1, now());

commit;